name: Branch Snapshot

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to publish snapshot of'
        required: true
        default: 'master'
      repository:
        description: 'Repository name (override for forks)'
        required: false
        default: Netflix/zuul
      version:
        description: 'The version number to use'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git
        run: |
          git config --global user.name 'Zuul Build'
          git config --global user.email 'zuul-build@netflix.com'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}
          repository: ${{ github.event.inputs.repository }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: Build snapshot
        run: ./gradlew build snapshot -Prelease.version="$BUILD_VERSION"
        env:
          BUILD_VERSION: ${{ github.event.inputs.version }}
          NETFLIX_OSS_SIGNING_KEY: ${{ secrets.ORG_SIGNING_KEY }}
          NETFLIX_OSS_SIGNING_PASSWORD: ${{ secrets.ORG_SIGNING_PASSWORD }}
          NETFLIX_OSS_REPO_USERNAME: ${{ secrets.ORG_NETFLIXOSS_USERNAME }}
          NETFLIX_OSS_REPO_PASSWORD: ${{ secrets.ORG_NETFLIXOSS_PASSWORD }}
